package app.mcorg.pipeline.project

sealed interface GetProjectsFailure
sealed interface GetProjectFailure
sealed interface CreateProjectFailure
sealed interface DeleteProjectFailure
sealed interface AssignProjectFailure
