version: 2
updates:
  - package-ecosystem: maven
    directory: /webapp
    schedule:
      interval: weekly
      day: monday

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
