springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /
  api-docs:
    path: /api-docs
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: TODO
        jwk-set-uri: TODO
# TODO: Data connections
