"""One-shot: emit item-glyph.css with tint classes whose contrast clears 3:1 on Seam's paper.

Minecraft's own dye/wood palette is the starting point, but several values are far too light to be
legible as a line icon on --bg-surface (#F7F0DE). WCAG 1.4.11 wants >=3:1 for a non-text graphic, so
each tint is darkened toward black until it clears that, preserving hue.
"""
import os

# Paths are relative to webapp/, so the script runs from anywhere.
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))

PAPER = (0xF7, 0xF0, 0xDE)
TARGET = 3.0

BASE = {
    "colour": {
        "white": "#E9ECEC", "orange": "#F07613", "magenta": "#BD44B3", "light_blue": "#3AB3DA",
        "yellow": "#F8C627", "lime": "#70B919", "pink": "#ED8DAC", "gray": "#3E4447",
        "light_gray": "#8E8E86", "cyan": "#158991", "purple": "#8932B7", "blue": "#3C44A9",
        "brown": "#835432", "green": "#5D7C15", "red": "#B02E26", "black": "#1D1D21",
    },
    "wood": {
        "oak": "#B08C51", "spruce": "#7A5A32", "birch": "#C8B187", "jungle": "#A9683B",
        "acacia": "#A85B31", "dark_oak": "#4B3520", "mangrove": "#733A38", "cherry": "#E3B0B4",
        "pale_oak": "#EDE5D4", "bamboo": "#C8B457", "crimson": "#8D3E5E", "warped": "#2E7A78",
    },
    "metal": {
        "wooden": "#B08C51", "stone": "#8E8E86", "copper": "#C97C4F", "iron": "#D8D8D8",
        "golden": "#F5D14B", "diamond": "#4AEDD9", "netherite": "#3A3238",
        "chainmail": "#9A9A9A", "leather": "#8B5A2B", "turtle": "#6C8C3F",
    },
    "oxidation": {
        "copper": "#C97C4F", "exposed": "#A87D5F", "weathered": "#7FA089", "oxidized": "#5BA07C",
    },
}


def srgb_to_lin(c):
    c = c / 255.0
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def luminance(rgb):
    r, g, b = (srgb_to_lin(c) for c in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def contrast(a, b):
    la, lb = luminance(a), luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


def parse(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def fmt(rgb):
    return "#%02X%02X%02X" % rgb


MIN_SEPARATION = 28  # Euclidean RGB distance below which two tints read as the same colour.


def distance(a, b):
    return sum((x - y) ** 2 for x, y in zip(a, b)) ** 0.5


def resolve(rgb, taken):
    """Darken toward black until the tint clears TARGET *and* is distinct from those already
    assigned on this axis.

    Clamping each tint independently to the 3:1 floor is not enough: every near-white neutral lands
    on the lightest passing grey, so white, light_gray, stone, iron and chainmail all collapse onto
    the same value and the ramp stops carrying any meaning. Assigning lightest-first and pushing
    each subsequent collision further down preserves the ordering that made the ramp readable.
    """
    for i in range(0, 101):
        f = 1 - i / 100.0
        cand = tuple(max(0, int(round(c * f))) for c in rgb)
        if contrast(cand, PAPER) >= TARGET and all(distance(cand, t) >= MIN_SEPARATION for t in taken):
            return cand, i > 0
    return (0, 0, 0), True


out = [
    "/* Item glyph tints — generated by webapp/scripts/gen-item-glyph-tints.py, do not hand-edit.",
    " *",
    " * A glyph is drawn once and tinted by CSS `color`, which its `currentColor` strokes inherit.",
    " * Minecraft's own dye/wood palette is the base; values too light to read on --bg-surface are",
    " * darkened toward black until they clear 3:1 (WCAG 1.4.11, non-text contrast), hue preserved.",
    " */",
    "",
    ".item-glyph {",
    "    display: inline-block;",
    "    vertical-align: -0.125em;",
    "    color: var(--text-primary);",
    "    flex: none;",
    "}",
    "",
    "/* No rule covers this id — deliberately conspicuous so a gap is reported, not absorbed. */",
    ".item-glyph--unmapped {",
    "    color: var(--red);",
    "    opacity: 0.55;",
    "}",
    "",
]

adjusted = []
for axis, tints in BASE.items():
    out.append("/* --- %s --- */" % axis)
    # Lightest first, so a collision pushes the already-darker tint further down rather than
    # dragging the lighter one into it.
    order = sorted(tints, key=lambda n: luminance(parse(tints[n])), reverse=True)
    taken = []
    assigned = {}
    for name in order:
        rgb = parse(tints[name])
        fixed, changed = resolve(rgb, taken)
        taken.append(fixed)
        assigned[name] = fixed
        if changed:
            adjusted.append((axis, name, tints[name], fmt(fixed),
                             round(contrast(rgb, PAPER), 2), round(contrast(fixed, PAPER), 2)))
    for name in tints:  # emit in the declared order, not the processing order
        out.append(".item-glyph--%s { color: %s; }" % (name.replace("_", "-"), fmt(assigned[name])))
    out.append("")

path = "mc-web/src/main/resources/static/styles/components/item-glyph.css"
open(path, "w").write("\n".join(out))

print("wrote %s" % path)
print("\ndarkened for contrast (%d of %d):" % (adjusted and len(adjusted) or 0,
                                               sum(len(v) for v in BASE.values())))
for axis, name, was, now, cw, cn in adjusted:
    print("  %-10s %-11s %s (%.2f:1) -> %s (%.2f:1)" % (axis, name, was, cw, now, cn))
