springdoc:
  swagger-ui:
    disable-swagger-default-url: true
    path: /
  api-docs:
    path: /api-docs
management:
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true
spring:
  data:
    mongodb:
      uri: mongodb+srv://java_client:${MONGODB_PASSWORD}@mc-org-db.edc7h.mongodb.net/mc-org-db
      database: mc-org-db
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://kind-gull-82.clerk.accounts.dev
          jwk-set-uri: https://kind-gull-82.clerk.accounts.dev/.well-known/jwks.json
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_CLIENT_USERNAME:guest}
    password: ${RABBITMQ_CLIENT_PASSWORD:guest}
  cloud:
    function:
      definition: authorityAddedConsumer;authorityChangedConsumer;authorityRemovedConsumer;userDeletedConsumer;teamCreatedConsumer;teamNameChangedConsumer;teamDeletedConsumer;
    stream:
      bindings:
        authorityAddedConsumer-in-0:
          destination: authority-added-events
          group: world
        authorityChangedConsumer-in-0:
          destination: authority-changed-events
          group: world
        authorityRemovedConsumer-in-0:
          destination: authority-removed-events
          group: world
        userDeletedConsumer-in-0:
          destination: user-deleted-events
          group: world
        teamCreatedConsumer-in-0:
          destination: team-created-events
          group: world
        teamNameChangedConsumer-in-0:
          destination: team-name-changed-events
          group: world
        teamDeletedConsumer-in-0:
          destination: team-deleted-events
          group: world
