app = 'mcorg'
primary_region = 'arn'

[build]

[env]
  DB_URL = 'jdbc:postgresql://ep-icy-wood-a2vogqwy-pooler.eu-central-1.aws.neon.tech/mcorg?sslmode=require'
  DB_USER = 'mcorg_owner'
  ENV = 'PRODUCTION'
  SKIP_MICROSOFT_SIGN_IN = 'false'
  MODRINTH_BASE_URL='https://staging-api.modrinth.com'
  MICROSOFT_LOGIN_BASE_URL='https://login.microsoftonline.com'
  XBOX_AUTH_BASE_URL='https://user.auth.xboxlive.com'
  XSTS_AUTH_BASE_URL='https://xsts.auth.xboxlive.com'
  MINECRAFT_BASE_URL='https://api.minecraftservices.com'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
