name: Clean up Preview Deployment
on:
  workflow_dispatch:
  pull_request:
    types: [closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} # You can generate a Fly API token in your account settings

jobs:
  delete-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Fly app
        uses: superfly/fly-pr-review-apps@1.2.0
  delete-neon:
    runs-on: ubuntu-22.04
    steps:
      - name: Delete Neon Branch
        uses: neondatabase/delete-branch-action@v3.2.0
        with:
          project_id: ${{ vars.NEON_PROJECT_ID }}
          branch: dev/pr-${{ github.event.number }}
          api_key: ${{ secrets.NEON_API_KEY }}