name: Test

on:
  pull_request:
    branches: [master]
    paths:
      - webapp/**/src/**
      - webapp/pom.xml
      - webapp/*/pom.xml

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v6
      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Cache Minecraft server data
        uses: actions/cache@v5
        with:
          path: webapp/mc-data/src/test/resources/servers/extracted
          key: minecraft-server-data-${{ hashFiles('webapp/mc-data/src/test/kotlin/app/mcorg/data/minecraft/extract/ServerFileDownloader.kt') }}
          restore-keys: |
            minecraft-server-data-
      - name: Generate JWT signing keys
        working-directory: ./webapp/mc-web
        run: bash create-keys.sh
      - name: Run unit tests
        run: mvn test -B

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webapp
    steps:
      - uses: actions/checkout@v6
      - name: Cache Maven packages
        uses: actions/cache@v5
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: '21'
      - name: Generate JWT signing keys
        working-directory: ./webapp/mc-web
        run: bash create-keys.sh
      - name: Build modules
        run: mvn install -DskipTests -B
      - name: Run database tests
        run: mvn test -pl mc-web -Dsurefire.excludedGroups= -Dgroups=database -B
